CREATE TABLE public.contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  worker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  employer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- e.g., 'pending', 'active', 'completed', 'terminated'
  
  PRIMARY KEY (id)
);

ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own contracts." ON public.contracts
  FOR SELECT USING (auth.uid() = worker_id OR auth.uid() = employer_id);

CREATE POLICY "Employers can create contracts." ON public.contracts
  FOR INSERT WITH CHECK (auth.uid() = employer_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Household');

CREATE POLICY "Users can update their own contracts." ON public.contracts
    FOR UPDATE USING (auth.uid() = worker_id OR auth.uid() = employer_id);
