-- Create a table for public profiles
CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  updated_at TIMESTAMP WITH TIME ZONE,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL,
  -- For Domestic Workers
  skills TEXT[],
  experience TEXT,
  availability TEXT,
  hourly_rate NUMERIC,
  -- For Households
  address TEXT,
  family_members INT,

  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Create a table for jobs
CREATE TABLE public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  household_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT,
  salary NUMERIC,
  job_type TEXT, -- e.g., 'full-time', 'part-time', 'one-time'
  
  PRIMARY KEY (id)
);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Jobs are viewable by everyone." ON public.jobs
  FOR SELECT USING (true);
  
CREATE POLICY "Households can create jobs." ON public.jobs
  FOR INSERT WITH CHECK (auth.uid() = household_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Household');

CREATE POLICY "Households can update their own jobs." ON public.jobs
  FOR UPDATE USING (auth.uid() = household_id);
  
CREATE POLICY "Households can delete their own jobs." ON public.jobs
  FOR DELETE USING (auth.uid() = household_id);
  

-- Create a table for job applications
CREATE TABLE public.job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  worker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- e.g., 'pending', 'accepted', 'rejected'
  
  PRIMARY KEY (id)
);

ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Workers can create applications." ON public.job_applications
  FOR INSERT WITH CHECK (auth.uid() = worker_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Domestic Worker');

CREATE POLICY "Users can view their own applications." ON public.job_applications
  FOR SELECT USING (auth.uid() = worker_id OR auth.uid() = (SELECT household_id FROM jobs WHERE id = job_id));
  
CREATE POLICY "Households can update application status." ON public.job_applications
  FOR UPDATE USING (auth.uid() = (SELECT household_id FROM jobs WHERE id = job_id));
